In [2]:
import numpy as np
a = np.array([0.22,0.24,0.30,0.24])
a*1900000

b = np.array([10.05,5.43,5.36,5.96])
c = np.array([196,1450,1250,1525])

(b * c * 1000 - a*1900000)/100000

array([15.518, 74.175, 61.3  , 86.33 ])

In [4]:
a=98.5+500+450+1800
b=196+1450+1250+1525

(b-a)/a *100

55.20449359311919

In [27]:
def _sum(arr):
 
    # initialize a variable
    # to store the sum
    # while iterating through
    # the array later
    sum = 0
 
    # iterate through the array
    # and add each element to the sum variable
    # one at a time
    for i in arr:
        sum = sum + i
 
    return(sum)

In [10]:
a = np.array([1,1,1,1])

b = np.array([0.56,0.48,0.36,0.61])

c = np.array([350,1850,1700,1200])

d = c*b

print(_sum(d))

_sum(c)-_sum(d)

2428.0


2672.0

In [24]:
def _sum(arr):
 
    # initialize a variable
    # to store the sum
    # while iterating through
    # the array later
    sum = 0
 
    # iterate through the array
    # and add each element to the sum variable
    # one at a time
    for i in arr:
        for j in i:
            sum = sum + j
 
    return(sum)
c = np.array([[8.04,10.05,15.00],[4.34,5.43,8.10],[4.29,5.36,8.00],[4.77,5.96,8.90]])
d = np.array([[98.5,196,350],[500,1450,1850],[450,1250,1700],[1800,1525,1200]])

print(c * d * 1000)
print("hah")
print(_sum(c * d * 1000))
_sum(c * d * 1000) / _sum(d * 1000)

[[  791940.  1969800.  5250000.]
 [ 2170000.  7873500. 14985000.]
 [ 1930500.  6700000. 13600000.]
 [ 8586000.  9089000. 10680000.]]
hah
83625740.0


6.76064028457092

In [29]:
d = np.array([[98.5,196,350],[500,1450,1850],[450,1250,1700],[1800,1525,1200]])
d
_sum(d)

array([2848.5, 4421. , 5100. ])

In [26]:
def lu(lst2):
    a,b = lst2
    print(round((b-a)*0.382+a,3))
    print(round((b-a)*0.618+a,3))
    
    return([(b-a)*0.382+a,(b-a)*0.618+a])



from math import e
def fe(lst):
    for i in lst:
        print(round(e**(-i)+i**2/2,3))
 
boundary=[0.382,0.764]

fe(lu(boundary))



0.528
0.618
0.729
0.73


In [33]:
import numpy as np

np.log(0.2)/np.log(0.618)

0.618*0.618*0.618*0.618

(np.log(0.2)-np.log(1))/np.log(0.618)


3.3441696797965283